name: DEV/STAGE Build Docker Image 
on:
  push:
    branches: [causeway-dev-1.3.1.0-gm]
jobs:
  build-gui:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      # - 
      #   name: RUN ENV
      #   id : runenv
      #   run: |
      #     env
      #     echo "Harbor fliite password is " 
      #     echo "$HARBORPWD"
      #     echo "pwd=$HARBORPWD" >> "$GITHUB_OUTPUT"
      # - 
      #   name: Docker Login to HARBOR.FLIITE.SYSTEMS
      #   uses: docker/login-action@v3.0.0
      #   with:
      #     registry: http://harbor.fliite.systems
      #     username: yash
      #     password: ${{ steps.runenv.outputs.pwd }}
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0    
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - 
        name: build from DOCKERFILE
        run: |
          docker build . --file Dockerfile --tag causewaygui:1.3.1.0arm-gm
          # docker push harbor.fliite.systems/geminos/causewayapi:1.3.1.0arm
